package lk.ijse.HIBERNATE_COURSE_WORK.navigation;
/* 
    @author Sachi_S_Bandara
    @created 3/13/2024 - 12:04 PM 
*/



public enum Routes {
  CREATEACCOUNT,ADDUSER,ADDBOOK,LOGOUT,USERLOGIN,USERBOOKS,USERBORROWDBOOKS,USERACCOUNT,ADMINLOGIN,ADMINBOOKS,ADMINUSERS,ADMINOVERDUEUSERS,ADMINBRANCHES,ADMINACCOUNT
}
